version: 0.0.0.{build}

shallow_clone: true
clone_depth: 1

configuration:
- MinSizeRel
- Release
- Debug

environment:
  DIST_DIR: '%APPVEYOR_BUILD_FOLDER%\dist'
  WATCOM: C:\Tools\watcom

  matrix:

    - APPVEYOR_BUILD_WORKER_IMAGE: 'Visual Studio 2015'
      VCVARSALL: '%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat'
      ARCHITECTURE: amd64_x86
      ARCHIVE: VS2015_%CONFIGURATION%_WIDE_x86_%APPVEYOR_BUILD_NUMBER%
      GENERATOR: 'NMake Makefiles'
      CMAKE_ARGS: 

    - APPVEYOR_BUILD_WORKER_IMAGE: 'Visual Studio 2015'
      VCVARSALL: '%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat'
      ARCHITECTURE: amd64
      ARCHIVE: VS2015_%CONFIGURATION%_WIDE_x64_%APPVEYOR_BUILD_NUMBER%
      GENERATOR: 'NMake Makefiles'
      CMAKE_ARGS: 

    - APPVEYOR_BUILD_WORKER_IMAGE: 'Visual Studio 2017'
      VCVARSALL: '%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat'
      ARCHITECTURE: amd64_x86
      ARCHIVE: VS2017_%CONFIGURATION%_WIDE_x86_%APPVEYOR_BUILD_NUMBER%
      GENERATOR: 'NMake Makefiles'
      CMAKE_ARGS: 

    - APPVEYOR_BUILD_WORKER_IMAGE: 'Visual Studio 2017'
      VCVARSALL: '%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat'
      ARCHITECTURE: amd64
      ARCHIVE: VS2017_%CONFIGURATION%_UTF8_x64_%APPVEYOR_BUILD_NUMBER%
      GENERATOR: 'NMake Makefiles'
      CMAKE_ARGS: 

init:
  - echo BUILD_NUMBER=%APPVEYOR_BUILD_NUMBER%

install:

  - cmake --version

build:
  parallel: true

build_script:

  - if exist "%VCVARSALL%" ( call "%VCVARSALL%" %ARCHITECTURE% )

  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir build
  - cd build

  - cmake %CMAKE_TOOLCHAIN_ARGS% -G"%GENERATOR%" -DCMAKE_VERBOSE_MAKEFILE=TRUE
          -DCMAKE_BUILD_TYPE=%CONFIGURATION% 
          "-DCMAKE_INSTALL_PREFIX=%DIST_DIR%\%APPVEYOR_BUILD_WORKER_IMAGE%"
          -DBUILD_NUMBER=%APPVEYOR_BUILD_NUMBER%
          ..

    cmake --build . --config %CONFIGURATION% --target install

after_build:
  - cd %DIST_DIR%
  - 7z a -tzip %ARCHIVE%.zip "%APPVEYOR_BUILD_WORKER_IMAGE%"
  - certutil -hashfile %ARCHIVE%.zip MD5 > %ARCHIVE%.md5

artifacts:
  - path: dist\$(ARCHIVE).zip
  - path: dist\$(ARCHIVE).md5
  